<template><div><blockquote>
<p>记录一些阅读deepspeed源码过程中的心得与感悟</p>
</blockquote>
<p>这里是一个我用cursor画的一个思维导图，大概描述了调用层级，所以就先从launcher开始看</p>
<Mermaid id="mermaid-8" code="eJyVVV1P21YYvudXWKkqbZIp2rgCTZUIH2238VGgtFBVkXFO4KyO7Tn2NnqVwhgsZEmAQmjYGqIOka0jAW0jEELzX1CO7V5tP2HnHB87Nmsr1RfRyfH7PM/77TlNUOe5yXAHh5/r17nW6Tla3kfZl+h4kd71PQz9WywkOUkwZHEeaF2aIctAu6EufDardd0k9rkqSpUdVOgR19l5kwsT0LODNsg5uCC7uWuV1xjueTn0yFGi0H4CTefa0Lgh6VBWoiASVEa/FuzUorV4Zjdzdind5ul3XOhwQzL3TlFzCTW2zM2MG1WY2gw8DF0Wnv9zmuUiEShDPRJxyaMAqAkVgOgNcg8FCT4BH33MBAYoeJA4mqly2CsdxkEXkOegDFyCAUwwQQgG6XUAOUSzk/SQKlSvwsfwlYT/vwV9ixUEyjGgAVm8Cr3j3ntYNxFvln+yLipuChy224Rtc83zRVTkGJz7XxT99Jr5cduJ33ceamskC61mCW2kUWrvTbKIq+LqDVLLO1SvxIlKPN5FNRgil7FeVZmAY/o5TVOaE0QRSEATdEVzEFbpj9b5iZm6sI9LvvBajR2U3iaKG+kZMD7qo/qCUn3vRfkEaIrDRQw9YED+S+ppilPUhGNqr/yOKoXW2Y9WJY8Ocz5ldHaCO9A63La29oPhDlPhPEdLTFnMv5+aR39Z9aYDCkiO0N4vcnGFGbdON1HlxKzVUG7VLJfQi7WA/Sh1McslwNcG7QRnMOpZtJp/C/0YNcejhdtCcHNZb5rJA+y0kwR/ULV9tFzDubR2180MMfFR3aVUq9hTPB5eXRxDigsIj+M5yx6TOVM1JQax/hxLRvLAXrpAqz+YL0g+24gJVjDB0BXdkD0AqUGqbB8tYXcDgEkC2HjN4ZUhPlYVKOtM4WXSLO7jLeGfg1c7Vv0ApYpEOxDWPTbTQBISOhShvsBS2jgjrlYOrfOlgOwUAeR/JqHhjlY1kEhARWbStGAos2Y1fguA7rPtGFeihgTw5vkKiK67GPNL3vyTrNMA5gGNr8nJ3+D2paYjU8PgHUUzn1XNjXU3tIQx62z5kP9tiL4jzzSh3t0jMRg6lFi3s/KvXJhbR8wT8sywPEM2P/brTewq+V2p+8z68Gfjcucp4ZTBrCEJrJ/r63alhOfHZxrGH4vLAt0IKpRYcFZj266ue+EROyBHnTCdhEz7zjO+c9i/+GuokXVmlt6JuKyJARDDXLq2MEa6hMPtKPVei8V68MMndE15DHqvdXd3s3PntzCqz/d2q98FGURFYwuWMfT0iGIs9m6GT68yqIImSBKQPDzx4QPwCUNVFa0dgCi+D/4Jhrfx+FvbToHvepAf4m/5YvO9GuZH+FF+zHPb9+ouP85P8JP8PX6Kv88/4Kf5Gb6vjw+HXR87/gPhkUZi"></Mermaid><h2 id="一-launcher" tabindex="-1"><a class="header-anchor" href="#一-launcher"><span>一. Launcher</span></a></h2>
<blockquote>
<p>deepspeed/launcher/</p>
</blockquote>
<p>这里是整个deepspeed启动训练任务的入口，首先是<code v-pre>runner.py</code>, 它会根据单机or多机分配到<code v-pre>launch.py</code>或者<code v-pre>multinode_runner.py</code>.</p>
<p>暂且不考虑单worker的情况，因为太简单了，launcher最难的地方其实就是多机的初始化和通信，这里我们首先要知道一些细节，这里针对GPU多机多卡训练的通信介绍一些知识</p>
<h3 id="_1-communication" tabindex="-1"><a class="header-anchor" href="#_1-communication"><span>1. communication</span></a></h3>
<ol>
<li>物理层传输：底层通信是指底层硬件的物理层传输，这些是硬件自带的能力，这里分为intranode以及internode，intranode是单机多卡内的通信，internode是多机间通信</li>
</ol>
<ul>
<li>
<p>intranode：在NV GPU环境下，节点内通信直接使用NVLink即可，带宽达到900GB/s，下位方案是PCIe通用总线，带宽约32GB/s。</p>
</li>
<li>
<p>internode：首先就是InfiniBand，这是一种高速网络技术，支持RDMA，速度最快200Gbps+，下位方案是以太网TCP/UDP使用Socket的通信，只有大约10-100Gbps。</p>
</li>
</ul>
<ol start="2">
<li>通信库：软件层面的通信优化，可以在软件的层面上优化通信速度，选取合适的通信后端，同时也会提供故障重启，弹性扩缩容等操作。</li>
</ol>
<ul>
<li>
<p>MPI：高性能消息传输接口（Message Passing Interface），是一种通用的技术，例如OpenMPI，基于MPI标准，封装物理层能力（IB，TCP等等）提供多机间通信能力。</p>
</li>
<li>
<p>NCCL：如果是NV环境，那么就是MPI的上位替代，是NVIDIA发布的一个高效的集体通信库，专为多个GPU之间提供优化的传输效率和简化应用而设计，采用RDMA技术加速，intranode使用NVLink，自动优化通信路径，减少网络拥塞，当然这是一个与物理层无关的软件抽象，所以如果NVLink不支持会降级为PCIe，所以例如IB，NVLink等均不构成<strong>强依赖</strong>。</p>
</li>
</ul>
<ol start="3">
<li>应用接口层：其实就是<code v-pre>torchrun</code>，我们可以看一下pytorch的doc，里面是这样说的</li>
</ol>
<blockquote>
<p>By default for Linux, the Gloo and NCCL backends are built and included in PyTorch distributed (NCCL only when building with CUDA). MPI is an optional backend that can only be included if you build PyTorch from source.</p>
</blockquote>
<p>也就是torch支持<code v-pre>gloo</code>的cpu训练以及<code v-pre>nccl</code>的gpu训练，<code v-pre>nccl</code>一般作为<code v-pre>gloo</code>的备选方案。</p>
<p>接下来回到launcher之中，deepspeed并没有使用torch，而是自己实现了一套launcher，可以让用户通过<code v-pre>--launcher</code>来选择，默认是PDSH，也可以选择OpenMPI等一些MPI通信，没有使用nccl，因为nccl局限于cuda。</p>
<h3 id="_2-network" tabindex="-1"><a class="header-anchor" href="#_2-network"><span>2. network</span></a></h3>
<p>既然是多机分布式训练，机器之间必然会产生通信，这里deepspeed提供了两种方式，一种是<code v-pre>ssh</code>, 这要求配置hostfile，并且每两个node之间需要可以ssh免密登录，另外一种模式是<code v-pre>no_ssh</code>, 这个时候多个node之间不会尝试ssh验证，原理是在每个node都启动一个训练进程，然后必须要手动指定<code v-pre>node_rank</code>, <code v-pre>master_addr</code>, <code v-pre>master_port</code>等一些信息。</p>
<p>对于<code v-pre>ssh</code>模式，我们会设置<code v-pre>node_rank</code>, <code v-pre>master_addr</code>, <code v-pre>master_port</code>等一些关键信息。对于<code v-pre>no_ssh</code>模式，这一切需要配置好。</p>
<p>经过上述的网络通信基础设置，最后多node会在每个node上启动一个<code v-pre>python -m deepspeed.launcher.launch</code>, 开始执行分布式训练进程。</p>
<h3 id="_3-subprocess" tabindex="-1"><a class="header-anchor" href="#_3-subprocess"><span>3. subprocess</span></a></h3>
<p>最后launcher这个包，会启动若干的进程，然后执行不同的事情。对于多node，我们肯定会先选择一个node登录，然后在这个node上执行一个runner进程，对于runner进程，关系如下图所示：</p>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">Runner</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (runner.py)</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">└──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Launcher</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (launch.py)</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Training</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Process</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (GPU </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">0</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Training</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Process</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (GPU </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Training</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Process</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> (GPU </span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91">2</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">)</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ...</span></span></code></pre>
</div><p>可以看出，runner是主进程，会接受一些参数做一些通信和网络的相关配置，之后对于多node而言，会在每个node上启动一个launcher进程，这个是每个node上都有的，用于管理训练进程。</p>
<p>具体的训练进程是运行在每个node的slots上的，如果当前node 8卡都需要参与，那么就会启动8个training process，代表具体的训练进程，launcher的目的是管理这些进程，不断地loop去看当前的train进程还有多少正在work，然后对于用户发送的SIGINT或者系统发送的SIGTERM，写一些优雅退出的handler去退出train进程。</p>
<p>我们需要传入一些参数，这些具体的参数，可以看deepspeed文档，这里就不多赘述。</p>
<p><strong>不过上述的launcher，似乎因为deepspeed版本过老的原因，如今都由pytorch解决了，直接torchrun即可</strong></p>
<h2 id="二-initialize" tabindex="-1"><a class="header-anchor" href="#二-initialize"><span>二. Initialize</span></a></h2>
<p>经过上述的launcher，我们成功在各个node上启动了自己的<code v-pre>train.py</code>, 接下来我们先提供一个官方的<code v-pre>train.py</code>, 然后依次剖析里面的细节。</p>
<p>我看的是<a href="https://github.com/deepspeedai/DeepSpeedExamples" target="_blank" rel="noopener noreferrer">deepspeed example</a> 里面的BERT pre-train脚本，在<code v-pre>training/bing_bert</code>之中</p>
<h3 id="_1-distribute" tabindex="-1"><a class="header-anchor" href="#_1-distribute"><span>1. distribute</span></a></h3>
<blockquote>
<p>deepspeed/comm/</p>
</blockquote>
<p>在<code v-pre>prepare_model_optimizer</code>中，使用了<code v-pre>deepspeed.init_distributed(dist_backend='nccl')</code>，借此我们可以看一下deepspeed的通信包是如何设计的。</p>
<p>deepspeed的通信包保持着和<code v-pre>torch.distributed</code>同样的API设计，方便用户迁移，阅读这部分代码感觉也可以为未来阅读<code v-pre>pytorch</code>源码打下基础。</p>
<p>可以看出comm包主要就各种通信op(all_reduce, all_gather)进行封装，首先将默认的<code v-pre>torch.distributed</code>封装为<code v-pre>TorchBackend</code>, 这意味着默认的backend，然后这里也支持用户定制属于自己的backend。对于封装的<code v-pre>TorchBackend</code>主要是更加的普适，对各个torch版本都适用。当然deepspeed也提供了一个自己的定制后端作为参照：<code v-pre>CCLBackend</code>Intel通信库。</p>
<p>通过<code v-pre>init_deepspeed_backend()</code>来选择自己的定制backend，如果cdb最后还是为None，就使用<code v-pre>TorchBackend</code></p>
<div class="language-python" data-highlighter="shiki" data-ext="python" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">if</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> cdb </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">is</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> None</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    init_deepspeed_backend</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">get_accelerator</span><span style="--shiki-light:#999999;--shiki-dark:#666666">().</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">communication_backend_name</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(),</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> timeout</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> init_method</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    set_backend</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    utils</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">logger</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">info</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">f</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">'cdb=</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">{</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">cdb</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">}</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">if</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> cdb </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">is</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> None</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> and</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> torch</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">distributed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">is_initialized</span><span style="--shiki-light:#999999;--shiki-dark:#666666">():</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">    # The user initialized torch.dist themselves, create cdb and short-circuit</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    cdb </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> TorchBackend</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">dist_backend</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> timeout</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> init_method</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    return</span></span></code></pre>
</div><p>目前看来这块代码还挺奇怪的，比较偏向于半成品，大致思路其实是想设计一个更加普适通用的通信后端框架，但是目前只是对<code v-pre>torch.distributed</code>进行了一次包装</p>
<p>和<code v-pre>launcher</code>模块面临的处境差不多，在启动分布式训练的时候确实可能需要很多的网络和通信的准备工作，但是现代pytorch已经将这些繁琐的工作收敛进torch之中，deepspeed这里的代码只能说有一定的启发作用。</p>
<p>目前对deepspeed的通信有了一定的了解，分为了两个部分，一个是init阶段，使用MPI来通信一些基本信息和环境变量，例如<code v-pre>LOCAL_RANK</code>这种，意思是如果没有设置这种rank，可以只通过指定若干host来让deepspeed帮你自动排序，最后注入环境变量。或者说这些基础环境变量完全由用户来指定，这样就不需要MPI了。第二个阶段是work阶段，这个时候就需要定制的通信后端，例如cpu使用<code v-pre>gloo</code>, nv gpu使用<code v-pre>nccl</code>, intel使用<code v-pre>ccl</code>等等, 这里强调的是高性能所以不能使用MPI。</p>
<h3 id="_2-deepspeed-initialize" tabindex="-1"><a class="header-anchor" href="#_2-deepspeed-initialize"><span>2. deepspeed.initialize</span></a></h3>
<blockquote>
<p>deepspeed/__init__.py</p>
</blockquote>
<p>重点来了，这里应该是deepspeed整个框架的初始化的汇集点, 第一部分的分布式环境初始化也应该是这个初始化的一部分。</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 初始化分布式环境</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">dist</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">init_distributed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">#初始化device mesh</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">dist</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">initialize_mesh_device</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mesh_param</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> (</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">data_parallel</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">sequence_parallel</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">))</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">if</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> not</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> isinstance</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">model</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> PipelineModule</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        config_class </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> DeepSpeedConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> mpu</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> mesh_device</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mesh_device</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">        if</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> config_class</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">hybrid_engine</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">enabled</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">            engine </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> DeepSpeedHybridEngine</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">        else</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">            engine </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> DeepSpeedEngine</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    else</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">        assert</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> mpu </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">is</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> None</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">mpu must be None with pipeline parallelism</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        mpu </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> model</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mpu</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        config_class </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> DeepSpeedConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> mpu</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        engine </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> PipelineEngine</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">    # Restore zero.Init context if necessary</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    zero</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">partition_parameters</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">restore_init_context</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    return_items </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> [</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        engine</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        engine</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">optimizer</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        engine</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">training_dataloader</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        engine</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">lr_scheduler</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    ]</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    return</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> tuple</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">return_items</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>可以看出deepspeed核心的计算和调度代码在<code v-pre>engine</code>之中，这个留到下一节讲。之后就是一个<code v-pre>if pp</code>的配置，首先GPU是由<code v-pre>device_mesh</code>组织的，目的是将GPU组织成一个网格结构，比如</p>
<div class="language-python" data-highlighter="shiki" data-ext="python" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">dist</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">initialize_mesh_device</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">mesh_param</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> (</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">data_parallel</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">sequence_parallel</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">))</span></span></code></pre>
</div><p>这里就是将各个worker组织成二维网格结构，第一行是dp的gpu group，第二行是sp的gpu group，这样做的好处就是不需要自己去划分不同的process group，更加便捷。不过我观察megatron并没有使用device mesh, 而是选择自己手动管理process group的形式，不知道有无什么讲究</p>
<p>然后就是构造engine，deepspeed将pp与dp+tp分割开了，看样子deepspeed并不支持3D parallel。不过也可以理解，deepspeed适合比较小的模型，走的是ZeRO这一套，如果是真正的大模型，还是需要使用megatron</p>
</div></template>
