<template><div><h2 id="一-ppo原理" tabindex="-1"><a class="header-anchor" href="#一-ppo原理"><span>一. PPO原理</span></a></h2>
<p>参考文章：<a href="https://zhuanlan.zhihu.com/p/677607581" target="_blank" rel="noopener noreferrer">通俗易懂的PPO解析</a></p>
<p>文章内分为两个部分，首先是基于<a href="https://github.com/deepspeedai/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat" target="_blank" rel="noopener noreferrer">DeepSpeedExample</a>来通俗地讲解了PPO算法，之后还有一篇PPO的理论解析. 本章主要是对其进行的完善补充，会涉及到更精细的code walkthrough, 然后还有更加基础和细致的PPO算法推导。</p>
<p>RL：Agent在一个Environment中，采取各种Action，目的是找到一个策略，这个策略根据当前观测到的环境状态和奖励反馈，来选择最佳的动作。</p>
<ul>
<li>Actor Model：<strong>参数更新</strong>，要训练的模型，会在Environment中采取一系列动作获得奖励。</li>
<li>Critic Model：<strong>参数更新</strong>，作用是预估收益</li>
<li>Reward Model：<strong>参数冻结</strong>，计算即时收益</li>
<li>Reference Model：<strong>参数冻结</strong>，使用KL散度约束Actor模型，不使其训偏。</li>
</ul>
<p>接下来就直接进入deepspeed-chat的源码走读环节，也会深入一些deepspeed的源码，讲解一下如何进行一次PPO RL训练。</p>
<h2 id="二-deepspeed-chat" tabindex="-1"><a class="header-anchor" href="#二-deepspeed-chat"><span>二. DeepSpeed-Chat</span></a></h2>
<p>接下来进行源码的走读，下面文章走读的master版本是这个<a href="https://github.com/deepspeedai/DeepSpeedExamples/tree/bd47e5bc38d292f44bf183e7bda992cde36a769b" target="_blank" rel="noopener noreferrer">DeepSpeed-Chat</a></p>
<p>RL训练的相关代码在application/DeepSpeed-Chat之中，大致分为三步</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> chat.py</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">  # 一个简单的聊天脚本，调用inference/chatbot.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> dschat</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">   # 一些代码实现，包括rlhf代码实现，和一些util的实现</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> rlhf</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ppo_trainer.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> rlhf_engine.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> utils</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> data</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> data_utils.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> raw_datasets.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ds_utils.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> model</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> model_utils.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> reward_model.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> module</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> lora.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> perf.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> utils.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> e2e_rlhf.py</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">   # 启动脚本，会调用training中的各个step</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> inference</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">     # 提供一个推理服务</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">│</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> chatbot.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">└──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> training</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">                          # 最核心的逻辑，对于每个阶段，提供了一个main.py，是具体的训练逻辑，</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> step1_supervised_finetuning</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">   # 然后将训练分为若干阶段，最后在training_scripts里面启动main.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> evaluation_scripts</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> run_prompt.sh</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> main.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> prompt_eval.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> training_log_output</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> opt-1.3b-globalBatchSize128.log</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> training_scripts</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 一些单机或者多机的不同种类模型的训练启动脚本</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> step2_dpo_finetuning</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> main.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> README.md</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> training_log_output</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> opt-350M_globalBatchSize-32.log</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> training_scripts</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 一些单机或者多机的不同种类模型的训练启动脚本</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> step2_reward_model_finetuning</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> evaluation_scripts</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> run_eval.sh</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> main.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> rw_eval.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> training_log_output</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> opt-350m_globalBatchSize-64.log</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> training_scripts</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">       ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 一些单机或者多机的不同种类模型的训练启动脚本</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">    └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> step3_rlhf_finetuning</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">        ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> BenckmarkSetting.md</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">        ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> main.py</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">        ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> training_log_output</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">        │</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">   └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> actor_opt-1.3b_critic_opt-350m_globalBatchSize64.log</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">        └──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> training_scripts</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">            ├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> 一些单机或者多机的不同种类模型的训练启动脚本</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们首先总览一下training包，里面是rlhf的step，第一个step是sft，里面是sft的逻辑，step2是reward model的ft，step3就是真正的rlft，每个step对应一个<code v-pre>main.py</code>来描述具体的逻辑，然后使用<code v-pre>training_scripts</code>来启动该step的训练。最后在最外层的<code v-pre>e2e_rlhf.py</code>里，调用training里面的scripts，这就是整个rlhf的训练过程，训练完成之后就可以使用<code v-pre>chat.py</code>调用inference相关代码，查看推理结果。</p>
<p>首先从training代码讲解，在training里面首先是step1：SFT。</p>
<h3 id="_1-step1-sft" tabindex="-1"><a class="header-anchor" href="#_1-step1-sft"><span>1. Step1: SFT</span></a></h3>
<ul>
<li><code v-pre>main.py</code></li>
</ul>
<p>首先<code v-pre>parse_args</code>来在deepspeed的基础上新增一些选项：</p>
<div class="language-python" data-highlighter="shiki" data-ext="python" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">parser </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> deepspeed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">add_config_arguments</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">parser</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">  # 和deepspeed的parser兼容</span></span></code></pre>
</div><p>然后进入main函数，解析args，之后是distributed相关配置</p>
<div class="language-python" data-highlighter="shiki" data-ext="python" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">get_accelerator</span><span style="--shiki-light:#999999;--shiki-dark:#666666">().</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">set_device</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">local_rank</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">device </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> torch</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">device</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">get_accelerator</span><span style="--shiki-light:#999999;--shiki-dark:#666666">().</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">device_name</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(),</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">local_rank</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># Initializes the distributed backend which will take care of sychronizing nodes/GPUs</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># torch.distributed.init_process_group(backend='nccl')</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">deepspeed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">init_distributed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">global_rank </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> torch</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">distributed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">get_rank</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span></code></pre>
</div><p>之后就是deepspeed的training的config配置, <code v-pre>train_micro_batch_size_per_gpu</code>感觉就是DP，分割batch
<code v-pre>train_batch_size</code>的计算方式是DP * world_size * gradient_accumulation_steps, gradient_accumulation_steps是一种训练优化技术，
如果gradient_accumulation_steps=2的话，意味着过了2个step才会去更新参数。</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ds_config </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> get_train_ds_config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">offload</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">offload</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                                dtype</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">dtype</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                                stage</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">zero_stage</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                                enable_tensorboard</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">enable_tensorboard</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                                tb_path</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">tensorboard_path</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                                tb_name</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">step1_model</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ds_config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">[</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">    '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">train_micro_batch_size_per_gpu</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">per_device_train_batch_size</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">ds_config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">[</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">    '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">train_batch_size</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">per_device_train_batch_size </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">*</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> torch</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">distributed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">get_world_size</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    )</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> *</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">gradient_accumulation_steps</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># If passed along, set the training seed now.</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">set_random_seed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">seed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">torch</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">distributed</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">barrier</span><span style="--shiki-light:#999999;--shiki-dark:#666666">()</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>之后load tokenizer和model, <code v-pre>load_hf_tokenizer</code>以及<code v-pre>create_hf_model</code>都实现在<code v-pre>dschat/util</code>之中</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># load_hf_tokenizer will get the correct tokenizer and set padding tokens based on the model family</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">additional_special_tokens </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">eot_token </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">if</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">add_eot_token </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">else</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> None</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">tokenizer </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> load_hf_tokenizer</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">model_name_or_path</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                                fast_tokenizer</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">True</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                                add_special_tokens</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">additional_special_tokens</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">model </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> create_hf_model</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">AutoModelForCausalLM</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">                        args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">model_name_or_path</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">                        tokenizer</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">                        ds_config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">                        dropout</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">dropout</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>看了一下<code v-pre>load_hf_tokenizer</code>相关代码，主要是依赖tansformers库中的方法，download云端的开源tokenizer或者导入本地的tokenizer
<code v-pre>from_pretrained</code>传入的参数是<code v-pre>model_name_or_path</code>, 可以指定本地的路径，但是格式需要符合Huggingface格式.</p>
<p>然后是一些配置选项，例如loss计算转为fp32提高精度，以及lora</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">if</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">compute_fp32_loss</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    print_rank_0</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">        f</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">"Using model </span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">{</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">model</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">__class__</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">__name__</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076">}</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> with loss in fp32"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">global_rank</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    causal_lm_model_to_fp32_loss</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">model</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">if</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">lora_dim </span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">></span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 0</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">    model </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> convert_linear_layer_to_lora</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">model</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">lora_module_name</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">                                            args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">lora_dim</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    if</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> args</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">only_optimize_lora</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        model </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> only_optimize_lora_parameters</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">model</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">        model </span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> make_model_gradient_checkpointing_compatible</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">model</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="https://zhuanlan.zhihu.com/p/12871616401" target="_blank" rel="noopener noreferrer">ray分布式训练</a></p>
<p><a href="https://github.com/zhaochenyang20/Awesome-ML-SYS-Tutorial/blob/main/rlhf/OpenRLHF/readme.md" target="_blank" rel="noopener noreferrer">openrlhf</a></p>
<p><a href="https://github.com/zhaochenyang20/Awesome-ML-SYS-Tutorial/blob/main/rlhf/verl/readme.md" target="_blank" rel="noopener noreferrer">verl</a></p>
</div></template>
