<template><div><p>主题内置的使用的插件，扩展了主题的众多功能，你可以在 <code v-pre>plugins</code> 配置中， 实现对内部使用的各个插件的自定义配置。</p>
<h2 id="配置" tabindex="-1"><a class="header-anchor" href="#配置"><span>配置</span></a></h2>
<p>所有主题内部使用的插件， 均在 <code v-pre>plugins</code> 字段中进行配置。</p>
<div class="code-block-title"><div class="code-block-title-bar"><span class="title"><VPIcon name="vscode-icons:file-type-typescript"/>.vuepress/config.ts</span></div><div class="language-js" data-highlighter="shiki" data-ext="js" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark has-diff vp-code twoslash lsp"><code><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">import</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#123;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> </span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>defineUserConfig</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">defineUserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: (</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">UserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">) => </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">UserConfig</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vuepress</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">import</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#123;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> </span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>plumeTheme</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> plumeTheme</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">options</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ThemeOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Theme</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vuepress-theme-plume</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">export</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> default</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>defineUserConfig</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> defineUserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">UserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> UserConfig</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">(&#123;</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">  </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>theme</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">theme</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Theme</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Vuepress theme</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@required</span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>plumeTheme</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> plumeTheme</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">options</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ThemeOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Theme</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">(&#123;</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">    </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>plugins</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ThemeOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">plugins</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> ThemeBuiltinPlugins</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>主题内置插件配置</p>
<p>请勿将此配置与 <a href="https://v2.vuepress.vuejs.org/zh/reference/config.html#plugins">vuepress plugins</a> 混淆</p></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#123;</span></span>
<span class="line diff add"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">      // more options...</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  }),</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">})</span></span></code></pre>
</div></div><h2 id="插件列表" tabindex="-1"><a class="header-anchor" href="#插件列表"><span>插件列表</span></a></h2>
<ul>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/features/nprogress.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-nprogress</a> - 页面加载进度条</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/features/photo-swipe.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-photo-swipe</a> - 图片预览</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/development/reading-time.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-reading-time</a> - 文章阅读时间</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/features/watermark.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-watermark</a> - 文章水印</li>
<li><RouteLink to="/notes/theme/config/plugins/search.html">@vuepress-plume/plugin-search</RouteLink> - 本地搜索</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/search/docsearch.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-docsearch</a> - Algolia 文档搜索</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/features/copy-code.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-copy-code</a> - 代码复制</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/markdown/shiki.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-shiki</a> - 代码高亮</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/blog/comment/" target="_blank" rel="noopener noreferrer">@vuepress/plugin-comment</a> - 文章评论</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/markdown/hint.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-markdown-hint</a> - Markdown 提示</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/markdown/image.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-markdown-image</a> - Markdown 图片</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/markdown/math.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-markdown-math</a> - Markdown 数学公式</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/markdown/include.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-markdown-include</a> - Markdown 导入文件</li>
<li><a href="https://plugin-md-enhance.vuejs.press/zh/" target="_blank" rel="noopener noreferrer">vuepress-plugin-md-enhance</a> - Markdown 增强</li>
<li><RouteLink to="/notes/theme/config/plugins/markdown-power.html">vuepress-plugin-md-power</RouteLink> - Markdown Power</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/development/git.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-git</a> - git 提交信息</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/tools/cache.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-cache</a> - 页面编译缓存</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/seo/seo/" target="_blank" rel="noopener noreferrer">@vuepress/plugin-seo</a> - SEO 优化</li>
<li><a href="https://ecosystem.vuejs.press/zh/plugins/seo/sitemap/" target="_blank" rel="noopener noreferrer">@vuepress/plugin-sitemap</a> - 站点地图</li>
</ul>
<div class="hint-container tip">
<p class="hint-container-title">提示</p>
<p>您无需重复安装这些内置插件，也无需在 <a href="https://v2.vuepress.vuejs.org/zh/reference/config.html#plugins" target="_blank" rel="noopener noreferrer">vuepress配置 &gt; plugins</a> 中添加它们。主题已在内部完成了这些工作。</p>
</div>
</div></template>


