<template><div><p>这是一篇杂谈, 主要讲解了如何配置一个cuda舒服的开发环境, 包括代码补全, 错误检查, (目前感觉这俩就够用了...)</p>
<p>插件主要使用clangd, IDE这里使用的是vscode (其实如果使用clion会省下来很多麻烦, 但是一般cuda开发都需要ssh gpu机器, 我个人习惯使用vscode shh)</p>
<p>虚拟环境使用micromamba/conda, 所以很多路径需要我们手动指定, 但是优点是环境干净隔离.</p>
<p>我们知道cuda的核心开发工具包就是nv的cudatoolkit, 这个里面包含了lib和nvcc编译器.</p>
<p>主要有俩方面, 一个是你的vscode需要识别到你的clangd, 在该项目的<code v-pre>.vscode/settings.json</code>下配置:</p>
<div class="language-json line-numbers-mode" data-highlighter="shiki" data-ext="json" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">clangd.path</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">/path/to/your/clangd</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">clangd.arguments</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> [</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">    "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">--query-driver=/path/to/your/nvcc</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">    "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">--background-index</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">    "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">--header-insertion=never</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">    "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">--completion-style=detailed</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">    "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">--enable-config</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  ],</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">clangd.fallbackFlags</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> [</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">-I${workspaceFolder}/include</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>因为我们是cuda项目, 所以需要将<code v-pre>--query-driver</code>设置为nvcc编译器路径.</p>
<p>接下来让clangd插件能够识别我们的项目, 现在主要有两种方式:</p>
<ul>
<li>
<p>通过编写<code v-pre>CMakeLists.txt</code>来导出<code v-pre>compile_commands.json</code>, 之后<code v-pre>settings.json</code>下面的<code v-pre>clangd</code>参数指定<code v-pre>compile_commands.json</code>的路径就可以了. 方法是设置<code v-pre>--compile-commands-dir=${workspaceFolder}/xxx</code></p>
</li>
<li>
<p>通过<code v-pre>.clangd</code>文件来告诉<code v-pre>clangd</code>我的编译选项, 编译器以及include/lib等, 比较难受的是<code v-pre>.clangd</code>文件不支持访问环境变量, 所以一般都是直接指定完整的目录, 我这里给出如下环境变量定义:</p>
</li>
</ul>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">export</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> CONDA_PREFIX</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">your</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">conda</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">envs</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">dev</span></span></code></pre>
</div><p>因为conda/micromamba在下载lib的时候, 会将其重组, 将各个库的lib目录, bin目录等重组在一起, 所以网络上设置<code v-pre>--cuda-path</code>的方法可能不适用, 因为cudatoolkit已经被打乱重组到环境中了, 这里我们假定当前的虚拟环境叫<code v-pre>dev</code>.</p>
<p>一般通过<code v-pre>conda-forge</code>安装的库, 路径都比较固定, 所以下面的yaml配置文件你只需改变一下你的env路径,就可以了.</p>
<div class="language-yaml line-numbers-mode" data-highlighter="shiki" data-ext="yaml" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">CompileFlags</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">  Compiler</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /your/conda/envs/dev/bin/nvcc</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">  Add</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    -</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> -xcuda</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    -</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> --cuda-path=/your/conda/envs/dev</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    -</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> -I/your/conda/envs/dev/lib/python3.11/site-packages/nvidia/cuda_runtime/include</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    -</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> -I/your/conda/envs/dev/lib/python3.11/site-packages/torch/include</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    -</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> -I/your/conda/envs/dev/lib/python3.11/site-packages/torch/include/torch/csrc/api/include</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    -</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> -I/your/conda/envs/dev/targets/x86_64-linux/include</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    -</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> -D__CUDACC__</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    -</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> -lcudart</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    -</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> -std=c++20</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">Diagnostics</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">  Suppress</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> [</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">return-type-c-linkage</span><span style="--shiki-light:#999999;--shiki-dark:#666666">]</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>首先我们需要设置<code v-pre>-xcuda</code>来让clang知道这是cuda代码. 其次就是cuda的库, 比如<code v-pre>cuda_runtime</code>等等, 这些都包含在<code v-pre>targets/x86_64-linux/include</code>之中, 被重组了.</p>
<p>接着在cuda开发之中一般都需要使用<code v-pre>Torch</code>库, 比如<code v-pre>at::Tensor</code>等等, 这类库是使用虚拟环境内的<code v-pre>pip</code>安装的, 相当于套了层娃</p>
<p><code v-pre>-lcudart</code>是cuda运行时编译选项? <code v-pre>-D__CUDACC__</code>..... 其实很多选项我这里也没有很清楚, 当做挖个坑吧</p>
<p>上述配置在我自己的<code v-pre>CentOS</code> GPU环境机器上可以run起来, 正确地运行错误提示以及代码补全. 当然你如果有第三方库或者项目内头文件目录的依赖, 也需要在<code v-pre>.clangd</code>中加上你的-I, link起来, 当然这里只讨论补全和check, 编译是另外一回事, cuda库的编译一般是使用<code v-pre>setup.py</code></p>
</div></template>


