<template><div><h2 id="概述" tabindex="-1"><a class="header-anchor" href="#概述"><span>概述</span></a></h2>
<p>主题内置的代码高亮插件， 对代码块进行代码高亮。</p>
<p>关联插件：<a href="https://ecosystem.vuejs.press/zh/plugins/markdown/shiki.html" target="_blank" rel="noopener noreferrer">@vuepress/plugin-shiki</a></p>
<p>主题 使用 <a href="https://github.com/shikijs/shiki" target="_blank" rel="noopener noreferrer">Shiki</a> 在 Markdown 代码块中使用彩色文本实现语法高亮。
Shiki 支持多种编程语言。</p>
<p>在 Shiki 的代码仓库中，可以找到 <a href="https://shiki.style/languages" target="_blank" rel="noopener noreferrer">合法的编程语言列表</a> 。</p>
<h2 id="特性" tabindex="-1"><a class="header-anchor" href="#特性"><span>特性</span></a></h2>
<ul>
<li><RouteLink to="/notes/theme/guide/code/features.html#%E4%BB%A3%E7%A0%81%E5%9D%97%E6%A0%87%E9%A2%98">代码块标题</RouteLink></li>
<li><RouteLink to="/notes/theme/guide/code/features.html#%E5%9C%A8%E4%BB%A3%E7%A0%81%E5%9D%97%E4%B8%AD%E5%AE%9E%E7%8E%B0%E8%A1%8C%E9%AB%98%E4%BA%AE">代码行高亮</RouteLink></li>
<li><RouteLink to="/notes/theme/guide/code/features.html#%E4%BB%A3%E7%A0%81%E5%9D%97%E4%B8%AD%E8%81%9A%E7%84%A6">代码聚焦</RouteLink></li>
<li><RouteLink to="/notes/theme/guide/code/features.html#%E4%BB%A3%E7%A0%81%E5%9D%97%E4%B8%AD%E7%9A%84%E9%A2%9C%E8%89%B2%E5%B7%AE%E5%BC%82">代码对比差异</RouteLink></li>
<li><RouteLink to="/notes/theme/guide/code/features.html#%E9%AB%98%E4%BA%AE-%E9%94%99%E8%AF%AF-%E5%92%8C-%E8%AD%A6%E5%91%8A">代码高亮“错误”和“警告”</RouteLink></li>
<li><RouteLink to="/notes/theme/guide/code/features.html#%E4%BB%A3%E7%A0%81%E5%9D%97%E4%B8%AD-%E8%AF%8D%E9%AB%98%E4%BA%AE">代码词高亮</RouteLink></li>
<li><RouteLink to="/notes/theme/guide/code/features.html#%E6%8A%98%E5%8F%A0%E4%BB%A3%E7%A0%81%E5%9D%97">代码块折叠</RouteLink></li>
<li><RouteLink to="/notes/theme/guide/code/twoslash.html#twoslash">twoslash</RouteLink> ：在代码块内提供内联类型提示。</li>
</ul>
<h2 id="配置" tabindex="-1"><a class="header-anchor" href="#配置"><span>配置</span></a></h2>
<p>默认配置：</p>
<div class="code-block-title"><div class="code-block-title-bar"><span class="title"><VPIcon name="vscode-icons:file-type-typescript"/>.vuepress/config.ts</span></div><div class="language-ts" data-highlighter="shiki" data-ext="ts" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code twoslash lsp"><code><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">import</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#123;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> </span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>defineUserConfig</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">defineUserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: (</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">UserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">) => </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">UserConfig</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vuepress</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">import</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#123;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> </span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>plumeTheme</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> plumeTheme</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">options</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ThemeOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Theme</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vuepress-theme-plume</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">export</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> default</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>defineUserConfig</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> defineUserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">UserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> UserConfig</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">(&#123;</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">  </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>theme</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">theme</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Theme</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Vuepress theme</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@required</span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>plumeTheme</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> plumeTheme</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">options</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ThemeOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Theme</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">(&#123;</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">    </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>codeHighlighter</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ThemeFeatureOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">codeHighlighter</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> false</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> ShikiPluginOptions</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>代码块高亮配置，主题使用 <code>shiki</code> 作为代码块高亮器</p></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: &#123;</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>themes</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><pre class="shiki shiki-themes vitesse-light vitesse-dark" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212" tabindex="0"><code><span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ShikiDualThemeOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">themes</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">:</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#123;</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">    dark</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ShikiTheme</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">    light</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ShikiTheme</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span></code></pre></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>The dark and light themes to use</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@see</span><span class="twoslash-popup-docs-tag-value"><a href="https://shiki.style/themes">https://shiki.style/themes</a></span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: &#123; </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>light</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">light</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> ShikiTheme</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vitesse-light</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666">, </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>dark</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">dark</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> ShikiTheme</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vitesse-dark</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> },</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>notationDiff</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">notationDiff</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> boolean</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Enable notation diff transformer</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@default</span><span class="twoslash-popup-docs-tag-value">false</span></span><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@see</span><span class="twoslash-popup-docs-tag-value"><a href="https://shiki.style/packages/transformers#transformernotationdiff">https://shiki.style/packages/transformers#transformernotationdiff</a></span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">true</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>notationErrorLevel</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">notationErrorLevel</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> boolean</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Enable notation error level transformer</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@default</span><span class="twoslash-popup-docs-tag-value">false</span></span><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@see</span><span class="twoslash-popup-docs-tag-value"><a href="https://shiki.style/packages/transformers#transformernotationerrorlevel">https://shiki.style/packages/transformers#transformernotationerrorlevel</a></span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">true</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>notationFocus</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">notationFocus</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> boolean</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Enable notation focus transformer</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@default</span><span class="twoslash-popup-docs-tag-value">false</span></span><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@see</span><span class="twoslash-popup-docs-tag-value"><a href="https://shiki.style/packages/transformers#transformernotationfocus">https://shiki.style/packages/transformers#transformernotationfocus</a></span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">true</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>notationHighlight</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">notationHighlight</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> boolean</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Enable notation highlight transformer</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@default</span><span class="twoslash-popup-docs-tag-value">false</span></span><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@see</span><span class="twoslash-popup-docs-tag-value"><a href="https://shiki.style/packages/transformers#transformernotationhighlight">https://shiki.style/packages/transformers#transformernotationhighlight</a></span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">true</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>notationWordHighlight</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">notationWordHighlight</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> boolean</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Enable notation word highlight transformer</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@default</span><span class="twoslash-popup-docs-tag-value">false</span></span><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@see</span><span class="twoslash-popup-docs-tag-value"><a href="https://shiki.style/packages/transformers#transformernotationwordhighlight">https://shiki.style/packages/transformers#transformernotationwordhighlight</a></span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">true</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>highlightLines</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">highlightLines</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> boolean</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Enable highlight lines or not</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@default</span><span class="twoslash-popup-docs-tag-value">true</span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">true</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>collapsedLines</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">collapsedLines</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> number</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> boolean</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">disable</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Whether to collapse code blocks when they exceed a certain number of lines,</p>
<ul>
<li>If <code>number</code>, collapse starts from line <code>number</code>.</li>
<li>If <code>true</code>, collapse starts from line 15 by default.</li>
<li>If <code>false</code>, do not enable code block collapsing globally, but you can enable it for individual code blocks using <code>:collapsed-lines</code></li>
<li>If <code>'disable'</code>, Completely disable code block collapsing</li>
</ul></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@default</span><span class="twoslash-popup-docs-tag-value">'disable'</span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">false</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>lineNumbers</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">MarkdownItLineNumbersOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">lineNumbers</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> number</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> boolean</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">disable</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Show line numbers in code blocks</p>
<ul>
<li>If <code>number</code>, show line numbers with code block lines not less than <code>number</code>.</li>
<li>If <code>true</code>, show line number always</li>
<li>If <code>false</code>, do not enable line numbers globally, but you can enable it for individual code blocks using <code>:line-numbers</code></li>
<li>If <code>'disable'</code>, Completely disable line number</li>
</ul></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@default</span><span class="twoslash-popup-docs-tag-value">'disable'</span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">true</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    },</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">    // 也可以通过 plugins.shiki 配置，但不推荐</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">    </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>plugins</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ThemeOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">plugins</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> ThemeBuiltinPlugins</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>主题内置插件配置</p>
<p>请勿将此配置与 <a href="https://v2.vuepress.vuejs.org/zh/reference/config.html#plugins">vuepress plugins</a> 混淆</p></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: &#123;</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">      </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>shiki</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">ThemeBuiltinPlugins</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">shiki</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> false</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> ShikiPluginOptions</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>代码高亮 配置</p></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: &#123;}</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">    }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  }),</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">})</span></span></code></pre>
</div></div><h3 id="themes" tabindex="-1"><a class="header-anchor" href="#themes"><span>themes</span></a></h3>
<ul>
<li>类型: <code v-pre>{ light: string, dark: string }</code></li>
<li>默认值: <code v-pre>{ light: 'vitesse-light', dark: 'vitesse-dark' }</code></li>
</ul>
<p>代码高亮主题，支持 浅色/暗色 双主题。</p>
<p>可在 支持的 <a href="https://shiki.style/themes" target="_blank" rel="noopener noreferrer">主题列表</a> 中选择你喜欢的主题。</p>
<h3 id="langs" tabindex="-1"><a class="header-anchor" href="#langs"><span>langs</span></a></h3>
<ul>
<li>类型: <code v-pre>string[]</code></li>
<li>默认值: <code v-pre>[]</code></li>
</ul>
<p>需要高亮的编程语言， 例如 <code v-pre>javascript</code>、<code v-pre>typescript</code>、<code v-pre>python</code>、<code v-pre>java</code>、<code v-pre>c++</code>、<code v-pre>c#</code>等。
默认会根据代码块的语言自动识别。</p>
<p>在 Shiki 的代码仓库中，可以找到 <a href="https://shiki.style/languages" target="_blank" rel="noopener noreferrer">合法的编程语言列表</a> 。</p>
<h3 id="defaultlang" tabindex="-1"><a class="header-anchor" href="#defaultlang"><span>defaultLang</span></a></h3>
<ul>
<li>类型： <code v-pre>string</code></li>
<li>默认值： <code v-pre>text</code></li>
</ul>
<p>指定的语言不可用时所使用的备选语言。</p>
<h3 id="linenumbers" tabindex="-1"><a class="header-anchor" href="#linenumbers"><span>lineNumbers</span></a></h3>
<ul>
<li>类型：<code v-pre>boolean | number</code></li>
<li>默认值： <code v-pre>true</code></li>
</ul>
<p>是否显示行号。</p>
<p><code v-pre>true</code>： 显示行号<br>
<code v-pre>false</code>： 不显示行号<br>
<code v-pre>number</code>： 指定需要显式代码行号的最小行数。</p>
<h3 id="twoslash" tabindex="-1"><a class="header-anchor" href="#twoslash"><span>twoslash</span></a></h3>
<ul>
<li>类型: <code v-pre>boolean | ShikiTwoslashOptions</code></li>
<li>默认值: <code v-pre>false</code></li>
</ul>
<p>是否启用 对 <code v-pre>typescript</code> 和 <code v-pre>vue</code> 语言的 类型提示 支持。</p>
<h3 id="whitespace" tabindex="-1"><a class="header-anchor" href="#whitespace"><span>whitespace</span></a></h3>
<ul>
<li>类型: <code v-pre>boolean | 'all' | 'boundary' | 'trailing'</code></li>
<li>默认值: <code v-pre>false</code></li>
</ul>
<p>将空白字符（Tab 和空格）渲染为单独的标签（具有 tab 或 space 类名）。</p>
<p>效果：</p>
<div class="language-xml" data-highlighter="shiki" data-ext="xml" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">catalog</span><span style="--shiki-light:#999999;--shiki-dark:#666666">></span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">book</span><span style="--shiki-light:#999999;--shiki-dark:#666666">></span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">title</span><span style="--shiki-light:#999999;--shiki-dark:#666666">></span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">Everyday</span><span class="space"> </span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">Italian</span><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;/</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">title</span><span style="--shiki-light:#999999;--shiki-dark:#666666">></span></span>
<span class="line"><span class="space"> </span><span class="space"> </span><span class="space"> </span><span class="space"> </span><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;/</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">book</span><span style="--shiki-light:#999999;--shiki-dark:#666666">></span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;/</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">catalog</span><span style="--shiki-light:#999999;--shiki-dark:#666666">></span></span></code></pre>
</div><h3 id="collapsedlines" tabindex="-1"><a class="header-anchor" href="#collapsedlines"><span>collapsedLines</span></a></h3>
<ul>
<li>类型: <code v-pre>boolean | number</code></li>
<li>默认值： <code v-pre>false</code></li>
</ul>
<p>将代码块折叠到指定行数。</p>
<h3 id="transformers" tabindex="-1"><a class="header-anchor" href="#transformers"><span>transformers</span></a></h3>
<ul>
<li>类型: <code v-pre>ShikiTransformer[]</code></li>
<li>默认值: <code v-pre>[]</code></li>
</ul>
<p>代码转换器， 查看 <a href="https://shiki.style/guide/transformers" target="_blank" rel="noopener noreferrer">shiki transformers</a> 了解更多信息。</p>
</div></template>


