<template><div><h2 id="依赖环境" tabindex="-1"><a class="header-anchor" href="#依赖环境"><span>依赖环境</span></a></h2>
<ul>
<li><a href="https://nodejs.org/" target="_blank" rel="noopener noreferrer">Node.js</a> : <strong>^18.19.0 或 ^20.6.0 或 &gt;= 22.0.0</strong> <Annotation label="node-versions" :total="3"><template #item-0><p><strong>^18.19.0：</strong> <code v-pre>18.19.0</code> 及以上但不高于 <code v-pre>19.0.0</code> 的版本</p>
</template><template #item-1><p><strong>^20.6.0：</strong> <code v-pre>20.6.0</code> 及以上但不高于 <code v-pre>21.0.0</code> 的版本</p>
</template><template #item-2><p><strong>&gt;= 22.0.0：</strong> <code v-pre>22.0.0</code> 及以上的版本</p>
</template></Annotation></li>
<li><a href="https://www.npmjs.com/" target="_blank" rel="noopener noreferrer">npm 8+</a> 或 <a href="https://pnpm.io/zh/" target="_blank" rel="noopener noreferrer">pnpm 8+</a> 或 <a href="https://yarnpkg.com/" target="_blank" rel="noopener noreferrer">Yarn 2+</a></li>
</ul>
<details class="hint-container details"><summary>怎么安装依赖环境？</summary>
<div class="vp-steps"><ol>
<li>
<p><strong>请前往 <a href="https://nodejs.org/zh-cn" target="_blank" rel="noopener noreferrer">Node.js 官网</a> 下载最新稳定版本</strong></p>
<p>请根据指引完成安装，一般而言，在安装过程中，您只需要保持其默认设置，直接选择下一步即可。</p>
</li>
<li>
<p><strong>安装 PNPM</strong></p>
<p>在您安装完成 node.js 后，请打开 终端，执行如下命令：</p>
<div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">corepack</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> enable</span></span></code></pre>
</div><p>主题推荐您使用 pnpm 作为项目管理器。</p>
</li>
<li>
<p><strong>完成</strong></p>
</li>
</ol>
</div></details>
<h2 id="命令行安装" tabindex="-1"><a class="header-anchor" href="#命令行安装"><span>命令行安装 <Badge type="tip" text="推荐" /></span></a></h2>
<p>主题提供了一个 命令行工具，帮助您构建一个基本项目。您可以通过运行以下命令，启动 安装向导。</p>
<CodeTabs id="0" :data='[{"id":"pnpm"},{"id":"yarn"},{"id":"npm"}]' tab-id="npm-to-pnpm-yarn-npm"><template #title0="{ value, isActive }"><VPIcon name="vscode-icons:file-type-light-pnpm"/><span>pnpm</span></template><template #title1="{ value, isActive }"><VPIcon name="vscode-icons:file-type-yarn"/><span>yarn</span></template><template #title2="{ value, isActive }"><VPIcon name="logos:npm-icon"/><span>npm</span></template><template #tab0="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pnpm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> create</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vuepress-theme-plume@latest</span></span></code></pre>
</div></template><template #tab1="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">yarn</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> create</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vuepress-theme-plume@latest</span></span></code></pre>
</div></template><template #tab2="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> create</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vuepress-theme-plume@latest</span></span></code></pre>
</div></template></CodeTabs><p>启动向导后，您只需要回答几个简单的问题：</p>
<div class="language-ansi has-collapsed-lines collapsed" data-highlighter="shiki" data-ext="ansi" style="--vp-collapsed-lines:15;--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">┌</span><span style="--shiki-light:#2993a3;--shiki-light-font-weight:bold;--shiki-dark:#5eaab5;--shiki-dark-font-weight:bold">  Welcome to VuePress and vuepress-theme-plume !</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  Select a language to display / 选择显示语言</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  简体中文</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  您想在哪里初始化 VuePress？</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  ./my-project</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  站点名称：</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  My Vuepress Site</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  站点描述信息：</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  My Vuepress Site Description</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  是否使用多语言？</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  No</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  请选择站点默认语言</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  简体中文</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  是否使用 TypeScript？</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  Yes</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  请选择打包工具</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  Vite</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  部署方式：</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  Custom</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  是否初始化 git 仓库？</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  Yes</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  是否安装依赖？</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span><span style="--shiki-light:#393a3480;--shiki-dark:#dbd7ca77">  Yes</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">◇</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">   🎉 创建成功!</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">│</span></span>
<span class="line"><span style="--shiki-light:#aaaaaa;--shiki-dark:#777777">└</span><span style="--shiki-light:#393a34;--shiki-dark:#dbd7caee">  🔨 执行以下命令即可启动：</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">      cd ./my-project</span></span>
<span class="line"><span style="--shiki-light:#1e754f;--shiki-dark:#4d9375">      pnpm run docs:dev</span></span></code></pre>
<div class="collapsed-lines"></div></div><details class="hint-container details"><summary>怎么使用命令行工具？</summary>
<p>以 Windows 系统为例，你可以使用以下方法来启动 CMD 命令行工具：</p>
<ol>
<li>按下 <code v-pre>Win + R</code> 键打开 “运行” 对话框。</li>
<li>输入 <code v-pre>cmd</code> 并按下 Enter 键。 （也可以输入 <code v-pre>powershell</code> 来打开 PowerShell）</li>
</ol>
<p>注意此时 <code v-pre>cmd</code> 可能不在你期望的目录位置，你可以使用如下命令来切换到正确的目录：</p>
<div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">D:</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> # 此命令将切换到 D: 分区，进入其他分区请按照实际情况修改</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">cd</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> open-source</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> # 进入 D: 分区下的 open-source 目录</span></span></code></pre>
</div><p>此时，你就可以在这里输入 <code v-pre>pnpm create vuepress-theme-plume@latest</code> 来创建一个基本的项目了。</p>
<p>创建的项目将位于 <code v-pre>D:\open-source\my-project</code> 目录下。</p>
</details>
<h2 id="手动安装" tabindex="-1"><a class="header-anchor" href="#手动安装"><span>手动安装</span></a></h2>
<div class="hint-container info">
<p class="hint-container-title">提示</p>
<ul>
<li>使用 <a href="https://pnpm.io/zh/" target="_blank" rel="noopener noreferrer">pnpm</a> 时，你需要安装 <code v-pre>vue</code> 作为 peer-dependencies 。</li>
<li>使用 <a href="https://yarnpkg.com/" target="_blank" rel="noopener noreferrer">Yarn 2+</a> 时，你需要在 <code v-pre>.yarnrc.yml</code> 文件中设置 <code v-pre>nodeLinker: 'node-modules'</code> 。</li>
</ul>
</div>
<p>使用本主题，你需要首先新建一个项目，并安装<code v-pre>vuepress@next</code>以及本主题</p>
<div class="vp-steps"><ul>
<li>
<h3 id="新建文件夹并进入目录" tabindex="-1"><a class="header-anchor" href="#新建文件夹并进入目录"><span>新建文件夹并进入目录</span></a></h3>
<div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">mkdir</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> my-blog</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">cd</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> my-blog</span></span></code></pre>
</div></li>
<li>
<h3 id="初始化项目" tabindex="-1"><a class="header-anchor" href="#初始化项目"><span>初始化项目</span></a></h3>
<CodeTabs id="0" :data='[{"id":"pnpm"},{"id":"yarn"},{"id":"npm"}]' tab-id="npm-to-pnpm-yarn-npm"><template #title0="{ value, isActive }"><VPIcon name="vscode-icons:file-type-light-pnpm"/><span>pnpm</span></template><template #title1="{ value, isActive }"><VPIcon name="vscode-icons:file-type-yarn"/><span>yarn</span></template><template #title2="{ value, isActive }"><VPIcon name="logos:npm-icon"/><span>npm</span></template><template #tab0="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">git</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> init</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pnpm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> init</span></span></code></pre>
</div></template><template #tab1="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">git</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> init</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">yarn</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> init</span></span></code></pre>
</div></template><template #tab2="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">git</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> init</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> init</span></span></code></pre>
</div></template></CodeTabs></li>
<li>
<h3 id="安装相关依赖" tabindex="-1"><a class="header-anchor" href="#安装相关依赖"><span>安装相关依赖</span></a></h3>
<p>安装 <code v-pre>vuepress@next</code> 和 <code v-pre>vuepress-theme-plume</code> 作为本地依赖。</p>
<CodeTabs id="0" :data='[{"id":"pnpm"},{"id":"yarn"},{"id":"npm"}]' tab-id="npm-to-pnpm-yarn-npm"><template #title0="{ value, isActive }"><VPIcon name="vscode-icons:file-type-light-pnpm"/><span>pnpm</span></template><template #title1="{ value, isActive }"><VPIcon name="vscode-icons:file-type-yarn"/><span>yarn</span></template><template #title2="{ value, isActive }"><VPIcon name="logos:npm-icon"/><span>npm</span></template><template #tab0="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 安装 vuepress</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pnpm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> add</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -D</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vuepress@next</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vue</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 安装 主题和打包工具</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pnpm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> add</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -D</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vuepress-theme-plume</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> @vuepress/bundler-vite@next</span></span></code></pre>
</div></template><template #tab1="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 安装 vuepress</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">yarn</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> add</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -D</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vuepress@next</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vue</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 安装 主题和打包工具</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">yarn</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> add</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -D</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vuepress-theme-plume</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> @vuepress/bundler-vite@next</span></span></code></pre>
</div></template><template #tab2="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 安装 vuepress</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> i</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -D</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vuepress@next</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vue</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 安装 主题和打包工具</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> i</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -D</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vuepress-theme-plume</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> @vuepress/bundler-vite@next</span></span></code></pre>
</div></template></CodeTabs><div class="hint-container warning">
<p class="hint-container-title">注意</p>
<p>主题当前版本 已适配至 <code>vuepress@{{ vuepressVersion }}</code>，你应该安装这个版本的 VuePress。高于或低于这个版本，可能会存在潜在的兼容性问题。</p>
</div>
</li>
<li>
<h3 id="在-package-json-中添加-script" tabindex="-1"><a class="header-anchor" href="#在-package-json-中添加-script"><span>在 <code v-pre>package.json</code> 中添加 <code v-pre>script</code></span></a></h3>
<div class="code-block-title"><div class="code-block-title-bar"><span class="title"><VPIcon name="vscode-icons:file-type-node"/>package.json</span></div><div class="language-json" data-highlighter="shiki" data-ext="json" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">scripts</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">    "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">docs:dev</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vuepress dev docs</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">    "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">docs:build</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vuepress build docs</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span></code></pre>
</div></div><p><code v-pre>vuepress</code> 默认将文档源码放在 <code v-pre>docs</code> 目录下。</p>
</li>
<li>
<h3 id="将默认的临时目录和缓存目录添加到-gitignore-文件中" tabindex="-1"><a class="header-anchor" href="#将默认的临时目录和缓存目录添加到-gitignore-文件中"><span>将默认的临时目录和缓存目录添加到<code v-pre>.gitignore</code> 文件中</span></a></h3>
<CodeTabs id="153" :data='[{"id":".gitignore"},{"id":"sh"}]'><template #title0="{ value, isActive }"><VPIcon name="vscode-icons:file-type-git"/><span>.gitignore</span></template><template #title1="{ value, isActive }"><VPIcon name="vscode-icons:file-type-shell"/><span>sh</span></template><template #tab0="{ value, isActive }"><div class="language-txt" data-highlighter="shiki" data-ext="txt" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span>node_modules</span></span>
<span class="line"><span>.temp</span></span>
<span class="line"><span>.cache</span></span></code></pre>
</div></template><template #tab1="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">echo</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">node_modules</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> >></span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> .gitignore</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">echo</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">.temp</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> >></span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> .gitignore</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">echo</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">.cache</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> >></span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> .gitignore</span></span></code></pre>
</div></template></CodeTabs></li>
<li>
<h3 id="在-docs-vuepress-config-js-ts-中配置主题" tabindex="-1"><a class="header-anchor" href="#在-docs-vuepress-config-js-ts-中配置主题"><span>在 <code v-pre>docs/.vuepress/config.{js,ts}</code> 中配置主题</span></a></h3>
<div class="code-block-title"><div class="code-block-title-bar"><span class="title"><VPIcon name="vscode-icons:file-type-typescript"/>docs/.vuepress/config.ts</span></div><div class="language-ts" data-highlighter="shiki" data-ext="ts" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code twoslash lsp"><code><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">import</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#123;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> </span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>viteBundler</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">viteBundler</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: (</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">options</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ViteBundlerOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">) => </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">Bundler</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">@vuepress/bundler-vite</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">import</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#123;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> </span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>defineUserConfig</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">defineUserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: (</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">UserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">) => </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">UserConfig</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vuepress</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">import</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#123;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> </span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>plumeTheme</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> plumeTheme</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">options</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ThemeOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Theme</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">vuepress-theme-plume</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">export</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> default</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>defineUserConfig</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> defineUserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">config</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">UserConfig</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> UserConfig</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">(&#123;</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">  // 请不要忘记设置默认语言</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">  </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>lang</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">lang</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> string</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Language for the site</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@default</span><span class="twoslash-popup-docs-tag-value">'en-US'</span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">zh-CN</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">  </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>theme</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">theme</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Theme</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Vuepress theme</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@required</span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>plumeTheme</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> plumeTheme</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">options</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ThemeOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Theme</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">(&#123;</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">    // more...</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  }),</span></span>
<span class="line"><span style="--shiki-light:#998418;--shiki-dark:#B8A965">  </span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>bundler</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">bundler</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Bundler</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> |</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> undefined</span></code><div class="twoslash-popup-docs vp-doc" vp-content=""><p>Vuepress bundler</p></div><div class="twoslash-popup-docs twoslash-popup-docs-tags vp-doc" vp-content=""><span class="twoslash-popup-docs-tag"><span class="twoslash-popup-docs-tag-name">@required</span></span></div></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"><v-menu class="twoslash-hover" popper-class="shiki twoslash-floating vp-copy-ignore vp-code" theme="twoslash"><span>viteBundler</span><template v-slot:popper="&#123;}"><span class="twoslash-popup-container vp-copy-ignore" v-pre=""><code class="twoslash-popup-code"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> viteBundler</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">options</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">?</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ViteBundlerOptions</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Bundler</span></code></span></template></v-menu></span><span style="--shiki-light:#999999;--shiki-dark:#666666">(),</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">})</span></span></code></pre>
</div></div><div class="hint-container warning">
<p class="hint-container-title">不要忘记设置默认语言</p>
<p>无论是否需要使用 <strong>多语言</strong> ，你都应该为 VuePress 配置 正确 <code v-pre>lang</code> 选项值。
主题需要根据 <code v-pre>lang</code> 选项来确定语言环境文本。</p>
</div>
</li>
<li>
<h3 id="在-docs-目录下新建-readme-md-文件" tabindex="-1"><a class="header-anchor" href="#在-docs-目录下新建-readme-md-文件"><span>在 <code v-pre>docs</code> 目录下新建 <code v-pre>README.md</code> 文件</span></a></h3>
<p>声明首页配置。</p>
<div class="code-block-title"><div class="code-block-title-bar"><span class="title"><VPIcon name="flat-color-icons:info"/>README.md</span></div><div class="language-md" data-highlighter="shiki" data-ext="md" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#005CC5;--shiki-light-font-weight:bold;--shiki-dark:#79B8FF;--shiki-dark-font-weight:bold">---</span></span>
<span class="line"><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">home: true</span></span>
<span class="line"><span style="--shiki-light:#1C6B48;--shiki-light-font-weight:bold;--shiki-dark:#4D9375;--shiki-dark-font-weight:bold">---</span></span></code></pre>
</div></div></li>
<li>
<h3 id="在本地服务器启动你的文档站点" tabindex="-1"><a class="header-anchor" href="#在本地服务器启动你的文档站点"><span>在本地服务器启动你的文档站点</span></a></h3>
<CodeTabs id="0" :data='[{"id":"pnpm"},{"id":"yarn"},{"id":"npm"}]' tab-id="npm-to-pnpm-yarn-npm"><template #title0="{ value, isActive }"><VPIcon name="vscode-icons:file-type-light-pnpm"/><span>pnpm</span></template><template #title1="{ value, isActive }"><VPIcon name="vscode-icons:file-type-yarn"/><span>yarn</span></template><template #title2="{ value, isActive }"><VPIcon name="logos:npm-icon"/><span>npm</span></template><template #tab0="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pnpm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> docs:dev</span></span></code></pre>
</div></template><template #tab1="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">yarn</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> docs:dev</span></span></code></pre>
</div></template><template #tab2="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> run</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> docs:dev</span></span></code></pre>
</div></template></CodeTabs><p>VuePress 会在 <a href="http://localhost:8080" target="_blank" rel="noopener noreferrer">http://localhost:8080</a>
启动一个热重载的开发服务器。当修改 Markdown 文件时，浏览器中的内容也会自动更新。</p>
</li>
<li>
<h3 id="完成" tabindex="-1"><a class="header-anchor" href="#完成"><span>完成</span></a></h3>
</li>
</ul>
</div><h2 id="更新主题" tabindex="-1"><a class="header-anchor" href="#更新主题"><span>更新主题</span></a></h2>
<p>您可以直接在项目中运行以下命令检查是否有可用的更新：</p>
<CodeTabs id="0" :data='[{"id":"pnpm"},{"id":"yarn"},{"id":"npm"}]' tab-id="npm-to-pnpm-yarn-npm"><template #title0="{ value, isActive }"><VPIcon name="vscode-icons:file-type-light-pnpm"/><span>pnpm</span></template><template #title1="{ value, isActive }"><VPIcon name="vscode-icons:file-type-yarn"/><span>yarn</span></template><template #title2="{ value, isActive }"><VPIcon name="logos:npm-icon"/><span>npm</span></template><template #tab0="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pnpm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> dlx</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vp-update</span></span></code></pre>
</div></template><template #tab1="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">yarn</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> dlx</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vp-update</span></span></code></pre>
</div></template><template #tab2="{ value, isActive }"><div class="language-sh" data-highlighter="shiki" data-ext="sh" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npx</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> vp-update</span></span></code></pre>
</div></template></CodeTabs></div></template>


<script setup lang="ts">
const vuepressVersion = __VUEPRESS_VERSION__
</script>